# Generated by Django 4.2.9 on 2025-12-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('codename', models.CharField(help_text='Eindeutiger Code für diese Berechtigung (z.B. "view_reports")', max_length=100, unique=True, verbose_name='Codename')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('local', 'Lokal')], default='local', max_length=10, verbose_name='Geltungsbereich')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('website', models.ForeignKey(blank=True, help_text='Leer lassen für globale Berechtigungen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.website', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Berechtigung',
                'verbose_name_plural': 'Berechtigungen',
                'ordering': ['scope', 'name'],
                'unique_together': {('codename', 'website')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('local', 'Lokal')], default='local', max_length=10, verbose_name='Geltungsbereich')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='permissions_system.permission', verbose_name='Berechtigungen')),
                ('website', models.ForeignKey(blank=True, help_text='Leer lassen für globale Rollen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.website', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Rolle',
                'verbose_name_plural': 'Rollen',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Zugewiesen am')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen von')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='permissions_system.role', verbose_name='Rolle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('website', models.ForeignKey(blank=True, help_text='Für lokale Rollen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='accounts.website', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Benutzerrolle',
                'verbose_name_plural': 'Benutzerrollen',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'role', 'website')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted', models.BooleanField(default=True, help_text='False = Explizite Verweigerung (überschreibt Rollenzuweisung)', verbose_name='Gewährt')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Zugewiesen am')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: Temporäre Berechtigung', null=True, verbose_name='Läuft ab am')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen von')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='permissions_system.permission', verbose_name='Berechtigung')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions_direct', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('website', models.ForeignKey(blank=True, help_text='Für lokale Berechtigungen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_permission_assignments', to='accounts.website', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Benutzerberechtigung',
                'verbose_name_plural': 'Benutzerberechtigungen',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'permission', 'website')},
            },
        ),
    ]
