# Generated by Django 4.2.9 on 2025-12-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ssotoken'),
        ('permissions_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rolle', 'verbose_name_plural': 'Rollen'},
        ),
        migrations.RemoveField(
            model_name='role',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='role',
            name='website',
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope',
            field=models.CharField(choices=[('global', 'Global - Gilt für alle Websites'), ('local', 'Lokal - Nur für ausgewählte Website')], default='local', help_text='Global = Alle Websites, Lokal = Nur ausgewählte Website', max_length=10, verbose_name='Geltungsbereich'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Pflicht wenn Geltungsbereich "Lokal" ist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='accounts.website', verbose_name='Website'),
        ),
    ]
