# Generated by Django 4.2.9 on 2025-12-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domain')),
                ('callback_url', models.URLField(verbose_name='Callback URL')),
                ('client_id', models.CharField(max_length=255, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('auto_register_users', models.BooleanField(default=False, help_text='Erlaubt neuen Benutzern automatischen Zugang zu dieser Website', verbose_name='Automatische Benutzerregistrierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Benutzername')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nachname')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff-Status')),
                ('is_verified', models.BooleanField(default=False, verbose_name='E-Mail verifiziert')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registriert am')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Login')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('allowed_websites', models.ManyToManyField(blank=True, related_name='users', to='accounts.website', verbose_name='Erlaubte Websites')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-Adresse')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Letzte Aktivität')),
                ('expires_at', models.DateTimeField(verbose_name='Läuft ab am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.website')),
            ],
            options={
                'verbose_name': 'Benutzersitzung',
                'verbose_name_plural': 'Benutzersitzungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'website', 'is_active'], name='accounts_us_user_id_a48fbc_idx')],
            },
        ),
    ]
