# Generated by Django 4.2.9 on 2025-12-22 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False, verbose_name='Profil vollständig'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Straße'),
        ),
        migrations.AddField(
            model_name='user',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hausnummer'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_address',
            field=models.BooleanField(default=False, verbose_name='Adresse erforderlich'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_company',
            field=models.BooleanField(default=False, verbose_name='Firma erforderlich'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_date_of_birth',
            field=models.BooleanField(default=False, verbose_name='Geburtsdatum erforderlich'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_first_name',
            field=models.BooleanField(default=False, verbose_name='Vorname erforderlich'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_last_name',
            field=models.BooleanField(default=False, verbose_name='Nachname erforderlich'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_phone',
            field=models.BooleanField(default=False, verbose_name='Telefon erforderlich'),
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook'), ('github', 'GitHub'), ('microsoft', 'Microsoft'), ('apple', 'Apple')], max_length=50, verbose_name='Anbieter')),
                ('provider_user_id', models.CharField(max_length=255, verbose_name='Provider User ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail vom Provider')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nachname')),
                ('avatar_url', models.URLField(blank=True, verbose_name='Profilbild URL')),
                ('extra_data', models.JSONField(default=dict, verbose_name='Zusätzliche Daten')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
