# Generated by Django 4.2.9 on 2025-12-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_company_user_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='allowed_origins',
            field=models.JSONField(default=list, help_text='Liste von erlaubten Origins für CORS (z.B. ["https://example.com"])', verbose_name='Erlaubte Origins'),
        ),
        migrations.AddField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='Öffentlicher API Key für Client-seitige Anfragen', max_length=64, unique=True, verbose_name='API Key'),
        ),
        migrations.AddField(
            model_name='website',
            name='api_secret',
            field=models.CharField(blank=True, help_text='Geheimer API Key - NUR für Server-seitige Anfragen!', max_length=64, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='website',
            name='require_email_verification',
            field=models.BooleanField(default=False, verbose_name='E-Mail-Verifizierung erforderlich'),
        ),
    ]
