# Generated by Django 4.2.9 on 2025-12-22 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresettoken_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFADevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_key', models.CharField(help_text='Base32 encoded TOTP secret', max_length=32)),
                ('is_active', models.BooleanField(default=False, help_text='Whether MFA is enabled for this user')),
                ('backup_codes', models.TextField(blank=True, help_text='JSON-encoded list of backup codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, help_text='When MFA was first activated', null=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time MFA was successfully used', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Device',
                'verbose_name_plural': 'MFA Devices',
                'ordering': ['-created_at'],
            },
        ),
    ]
