# Generated by Django 4.2.9 on 2025-12-22 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mfadevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiry time (short-lived)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether token has been exchanged')),
                ('used_at', models.DateTimeField(blank=True, help_text='When token was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(help_text='Website requesting SSO', on_delete=django.db.models.deletion.CASCADE, related_name='sso_tokens', to='accounts.website')),
            ],
            options={
                'verbose_name': 'SSO Token',
                'verbose_name_plural': 'SSO Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_used'], name='accounts_ss_token_e643d5_idx'), models.Index(fields=['user', 'website'], name='accounts_ss_user_id_8446ad_idx')],
            },
        ),
    ]
