# Generated by Django 4.2.9 on 2025-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_ssotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lexware_contact_id',
            field=models.UUIDField(blank=True, help_text='UUID des Kontakts in Lexware', null=True, verbose_name='Lexware Kontakt-ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='lexware_customer_number',
            field=models.IntegerField(blank=True, help_text='Eindeutige Kundennummer aus Lexware', null=True, unique=True, verbose_name='Lexware Kundennummer'),
        ),
    ]
