# Generated by Django 4.2.9 on 2025-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_lexware_contact_id_user_lexware_customer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='client_id',
            field=models.CharField(blank=True, help_text='OAuth2 Client ID für SSO', max_length=255, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='website',
            name='client_secret',
            field=models.CharField(blank=True, help_text='OAuth2 Client Secret für SSO', max_length=255, verbose_name='Client Secret'),
        ),
    ]
