# Generated by Django 4.2.9 on 2025-12-26 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_website_client_id_alter_website_client_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert - für Server-zu-Server API-Calls', max_length=64, unique=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='website',
            name='api_secret',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert - geheimer Key für Server-Anfragen', max_length=64, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='website',
            name='client_id',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert - für OAuth2/SSO', max_length=255, unique=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='website',
            name='client_secret',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert - für OAuth2/SSO', max_length=255, verbose_name='Client Secret'),
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10, verbose_name='HTTP Methode')),
                ('path', models.CharField(db_index=True, max_length=500, verbose_name='Pfad')),
                ('query_params', models.TextField(blank=True, null=True, verbose_name='Query Parameter')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='Request Body')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='Response Body')),
                ('status_code', models.IntegerField(db_index=True, verbose_name='Status Code')),
                ('ip_address', models.CharField(db_index=True, max_length=45, verbose_name='IP-Adresse')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Headers')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Referer')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Dauer (Sekunden)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitstempel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_requests', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'status_code'], name='accounts_ap_timesta_580982_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_ap_user_id_eb8fa8_idx'), models.Index(fields=['ip_address', '-timestamp'], name='accounts_ap_ip_addr_24e06c_idx')],
            },
        ),
    ]
