# Generated by Django 4.2.9 on 2026-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_website_api_key_alter_website_api_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='require_website_access',
            field=models.BooleanField(default=False, help_text='Wenn aktiv, können sich nur Benutzer mit expliziter Berechtigung anmelden. Wenn deaktiviert, kann sich jeder anmelden.', verbose_name='Website-Zugriff erforderlich'),
        ),
    ]
